export const quotes = [
  "Allowing people to have a chance, that’s all it was ever about – was to give them the opportunity to avail themselves of a sound, quality education.",
  "…a more spirited kind of action…",
  "This was the year of the riots.  The buildings were brand new.  We were the first class to occupy the new buildings.  The buildings were concrete white, they were all white inside, and all of my classmates my first year were white.  I had one person who was of color and that was a person in gym, but it was very very intimidating.",
  "We had an emphasis or belief that we could really change society.  That we could really make a change – especially for me, I grew up in Newark, and you had seen a lot of things.  I had seen a lot of destruction, destructive lifestyles.  I saw people who were bright who never went anyplace in their life and it was a question that we were going to change this.  And it was that feeling that we were going to change this whole process that was going on.  We were going to be the group that starts something to happen.",
  "…what could be changed or would be different.  It was also the era of Kennedy, the New Frontier, an advent thing that people had a chance to change their destinies, to make a change in regards to the world.  I think there was a lot of those type of thought patterns.  You also had some terrific leaders at that time, or speakers, who were very motivating, like Malcom X and Martin Luther King.  You had a lot of inspiration.  It was, I think, the spirit of the time, a thought pattern of what could be accomplished.  You could do anything.  At that time man had not landed on the moon, that was 1969, but it was a point of achievement – if you try you could achieve anything.  You could make changes out of the impossible.",
  "I was discouraged from applying to Rutgers University.  I was number eight out of a class of 365 student at South Side High School.  Indeed, I was a competitive student, but I was encouraged to apply to Howard, to Fisk, and to Spelman.",
  "…and when I came out there were National Guard’s people on the corners with guns.  I mean, it’s a frightening experience.  It’s like what I imagine being in a hostile territory must be like.  It had a strange effect on me in that I tried to go on about my business as usual, as though nothing were taking place.  Because even when I saw the guards people there, I still was not aware that someone had been killed the night before.",
  "It brought attention to the problem.  It brought the press out.  It brought the community out.",
  "It’s time that people of color have a significant presence that equates with their presence in the community.",
  "Our goal of increasing significantly, really increasing the access for black students to the various campuses of Rutgers, was never the goal nor the motivation of University administration.  I don’t care how much lip service they paid to it.",
  "And my father would talk about his grandfather, and my great-grandfather, and he talked about slavery, and the destructive system of slavery, and how far black people had come who had come out of slavery, because it had just been a hundred years, it was about 1865.  And he was talking about he had wanted to go to college, and how it was so difficult, the hurdles that were put in his way.",
  "There’s no question that we, uniformly, as a group, felt that something had to be done and something drastic had to be done.",
  "They didn’t feel protected cause they didn’t feel that the troops were being called to protect them.  I think they felt on the other side.",
  "I think that most of the people in the community were terrified.  I think they were scared to death.  They were frightened when the tanks were rolling in the streets, and the police.  And people were assaulted by police on the streets.  It was just – it was real frightening, and I feel it probably scarred, forever, children who had to live through that.",
  "We are just as concerned as we were 20 years ago.  We are just as mindful, and we are just as watchful."
]
