// Auto-generated by power2d material generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';

export const BasicVertexSource = `// Auto-generated by power2d material generator. DO NOT EDIT.
attribute position: vec3<f32>;
attribute uv: vec2<f32>;
varying vUV: vec2<f32>;
uniform uniforms_time: f32;
uniform uniforms_color: vec3f;
uniform power2d_canvasWidth: f32;
uniform power2d_canvasHeight: f32;

struct BasicUniforms {
  time: f32,
  color: vec3f,
};

fn vertShader(position: vec2f, uv: vec2f, uniforms: BasicUniforms) -> vec2f {
  let wobble = sin((uv.x + uv.y + uniforms.time) * 6.283) * 2.0;
  return position + vec2f(wobble, wobble);
}

fn fragShader(uv: vec2f, uniforms: BasicUniforms) -> vec4f {
  let pulse = 0.5 + 0.5 * sin(uniforms.time * 2.0 + uv.x * 3.14159);
  return vec4f(uniforms.color * pulse, 1.0);
}

fn load_BasicUniforms() -> BasicUniforms {
  return BasicUniforms(
  uniforms.uniforms_time,
  uniforms.uniforms_color
  );
}

fn power2d_pixelToNDC(pixel: vec2f) -> vec4f {
  let ndcX = (pixel.x / uniforms.power2d_canvasWidth) * 2.0 - 1.0;
  let ndcY = -((pixel.y / uniforms.power2d_canvasHeight) * 2.0 - 1.0);
  return vec4f(ndcX, ndcY, 0.0, 1.0);
}

#define CUSTOM_VERTEX_DEFINITIONS
@vertex
fn main(input : VertexInputs) -> FragmentInputs {
#define CUSTOM_VERTEX_MAIN_BEGIN
  let uniformsValue = load_BasicUniforms();
  let pixelPos = vec2f(vertexInputs.position.x, vertexInputs.position.y);
  let uv = vertexInputs.uv;
  let adjustedPixelPos = vertShader(pixelPos, uv, uniformsValue);
  vertexOutputs.position = power2d_pixelToNDC(adjustedPixelPos);
  vertexOutputs.vUV = uv;
#define CUSTOM_VERTEX_MAIN_END
}

`;
export const BasicFragmentSource = `// Auto-generated by power2d material generator. DO NOT EDIT.
varying vUV: vec2<f32>;
uniform uniforms_time: f32;
uniform uniforms_color: vec3f;
uniform power2d_canvasWidth: f32;
uniform power2d_canvasHeight: f32;

struct BasicUniforms {
  time: f32,
  color: vec3f,
};

fn vertShader(position: vec2f, uv: vec2f, uniforms: BasicUniforms) -> vec2f {
  let wobble = sin((uv.x + uv.y + uniforms.time) * 6.283) * 2.0;
  return position + vec2f(wobble, wobble);
}

fn fragShader(uv: vec2f, uniforms: BasicUniforms) -> vec4f {
  let pulse = 0.5 + 0.5 * sin(uniforms.time * 2.0 + uv.x * 3.14159);
  return vec4f(uniforms.color * pulse, 1.0);
}

fn load_BasicUniforms() -> BasicUniforms {
  return BasicUniforms(
  uniforms.uniforms_time,
  uniforms.uniforms_color
  );
}

#define CUSTOM_FRAGMENT_DEFINITIONS
@fragment
fn main(input: FragmentInputs) -> FragmentOutputs {
#define CUSTOM_FRAGMENT_MAIN_BEGIN
  let uv = fragmentInputs.vUV;
  let uniformsValue = load_BasicUniforms();
  let color = fragShader(uv, uniformsValue);
  fragmentOutputs.color = color;
#define CUSTOM_FRAGMENT_MAIN_END
}

`;

function ensureVector3(value: BABYLON.Vector3 | readonly [number, number, number]): BABYLON.Vector3 {
  return value instanceof BABYLON.Vector3 ? value : BABYLON.Vector3.FromArray(value as readonly [number, number, number]);
}

export interface BasicUniforms {
  time: number;
  color: BABYLON.Vector3 | readonly [number, number, number];
}

export const BasicUniformDefaults: BasicUniforms = {
  time: 0,
  color: [0, 0, 0],
};

export const BasicUniformMeta = [
  {
    name: 'time',
    kind: 'f32',
    bindingName: 'uniforms_time',
  },
  {
    name: 'color',
    kind: 'vec3f',
    bindingName: 'uniforms_color',
  },
] as const;

export function setBasicUniforms(material: BABYLON.ShaderMaterial, uniforms: Partial<BasicUniforms>): void {
  if (!uniforms) {
    return;
  }
  if (uniforms.time !== undefined) {
    material.setFloat('uniforms_time', uniforms.time);
  }
  if (uniforms.color !== undefined) {
    material.setVector3('uniforms_color', ensureVector3(uniforms.color));
  }
}

export type BasicTextureName = never;
export const BasicTextureNames = [] as const;

export interface BasicMaterialDef {
  readonly uniformType: BasicUniforms;
  readonly textureNames: readonly never[];
  readonly vertexSource: string;
  readonly fragmentSource: string;
  readonly uniformMeta: typeof BasicUniformMeta;
  readonly uniformDefaults: BasicUniforms;
  readonly createMaterial: (scene: BABYLON.Scene, name?: string) => BasicMaterialInstance;
}

export interface BasicMaterialInstance {
  material: BABYLON.ShaderMaterial;
  setUniforms(uniforms: Partial<BasicUniforms>): void;
  setTexture(name: BasicTextureName, texture: BABYLON.BaseTexture): void;
  setCanvasSize(width: number, height: number): void;
  dispose(): void;
}

export function createBasicMaterial(scene: BABYLON.Scene, name: string = 'BasicMaterial'): BasicMaterialInstance {
  const vertexShaderName = `${name}VertexShader`;
  const fragmentShaderName = `${name}FragmentShader`;

  BABYLON.ShaderStore.ShadersStoreWGSL[vertexShaderName] = BasicVertexSource;
  BABYLON.ShaderStore.ShadersStoreWGSL[fragmentShaderName] = BasicFragmentSource;

  const material = new BABYLON.ShaderMaterial(name, scene, {
    vertex: name,
    fragment: name,
  }, {
    attributes: ['position', 'uv'],
    uniforms: ['uniforms_time', 'uniforms_color', 'power2d_canvasWidth', 'power2d_canvasHeight'],
    samplers: [],
    samplerObjects: [],
    shaderLanguage: BABYLON.ShaderLanguage.WGSL,
  });

  setBasicUniforms(material, BasicUniformDefaults);
  material.disableDepthWrite = true;
  material.depthFunction = BABYLON.Constants.ALWAYS;
  material.backFaceCulling = false;
  material.alphaMode = BABYLON.Engine.ALPHA_COMBINE;

  const handles: BasicMaterialInstance = {
    material,
    setUniforms: (uniforms) => setBasicUniforms(material, uniforms),
    setTexture: (name, texture) => material.setTexture(name, texture),
    setCanvasSize: (width, height) => {
      material.setFloat('power2d_canvasWidth', width);
      material.setFloat('power2d_canvasHeight', height);
    },
    dispose: () => {
      material.dispose(true, false);
      delete BABYLON.ShaderStore.ShadersStoreWGSL[vertexShaderName];
      delete BABYLON.ShaderStore.ShadersStoreWGSL[fragmentShaderName];
    },
  };

  return handles;
}

export const BasicMaterial: BasicMaterialDef = {
  uniformType: undefined as unknown as BasicUniforms,
  textureNames: BasicTextureNames,
  vertexSource: BasicVertexSource,
  fragmentSource: BasicFragmentSource,
  uniformMeta: BasicUniformMeta,
  uniformDefaults: BasicUniformDefaults,
  createMaterial: createBasicMaterial,
};

export default BasicMaterial;
