// Auto-generated by wgsl fragment generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';
import { CustomShaderEffect, type ShaderSource, type RenderPrecision, type UniformDescriptor, type ShaderUniforms, type Dynamic } from '../shaderFXBabylon';
export const AlphaThresholdVertexSource = `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
attribute position: vec3<f32>;
attribute uv: vec2<f32>;
varying vUV: vec2<f32>;

#define CUSTOM_VERTEX_DEFINITIONS
@vertex
fn main(input : VertexInputs) -> FragmentInputs {
#define CUSTOM_VERTEX_MAIN_BEGIN
  vertexOutputs.position = vec4<f32>(vertexInputs.position, 1.0);
  vertexOutputs.vUV = vertexInputs.uv;
#define CUSTOM_VERTEX_MAIN_END
}

`;
export const AlphaThresholdFragmentSources = [
  `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
varying vUV: vec2<f32>;
uniform uniforms_threshold: f32;
var src: texture_2d<f32>;
var srcSampler: sampler;

// Source fragment function
struct AlphaThresholdUniforms {
  threshold: f32,
};

fn pass0(uv: vec2f, uniforms: AlphaThresholdUniforms, src: texture_2d<f32>, srcSampler: sampler) -> vec4f {
  let color = textureSample(src, srcSampler, uv);
  // Round alpha to 0 or 1 based on threshold
  let newAlpha = select(0.0, 1.0, color.a > uniforms.threshold);
  return vec4f(color.rgb, newAlpha);
}

fn load_AlphaThresholdUniforms() -> AlphaThresholdUniforms {
  var result: AlphaThresholdUniforms;
  result.threshold = uniforms.uniforms_threshold;
  return result;
}

#define CUSTOM_FRAGMENT_DEFINITIONS
@fragment
fn main(input: FragmentInputs) -> FragmentOutputs {
#define CUSTOM_FRAGMENT_MAIN_BEGIN
  let uniforms_value = load_AlphaThresholdUniforms();
  let uv_local = fragmentInputs.vUV;
  let color = pass0(uv_local, uniforms_value, src, srcSampler);
  fragmentOutputs.color = color;
#define CUSTOM_FRAGMENT_MAIN_END
}

`, // pass0
] as const;
export const AlphaThresholdPassCount = 1 as const;
export const AlphaThresholdPrimaryTextureName = 'src' as const;

export const AlphaThresholdPassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const AlphaThresholdUniformMeta: UniformDescriptor[] = [
  {
    name: 'threshold',
    kind: 'f32',
    bindingName: 'uniforms_threshold',
  },
];

export interface AlphaThresholdUniforms {
  threshold: number;
}

export function setAlphaThresholdUniforms(material: BABYLON.ShaderMaterial, uniforms: Partial<AlphaThresholdUniforms>): void {
  if (!uniforms) {
    return;
  }
  if (uniforms.threshold !== undefined) {
    material.setFloat('uniforms_threshold', uniforms.threshold);
  }
}

export type AlphaThresholdTextureName = 'src';
export interface AlphaThresholdInputs {
  src: ShaderSource;
}

export interface AlphaThresholdMaterialHandles {
  material: BABYLON.ShaderMaterial;
  setTexture(name: AlphaThresholdTextureName, texture: BABYLON.BaseTexture): void;
  setTextureSampler(name: AlphaThresholdTextureName, sampler: BABYLON.TextureSampler): void;
  setUniforms(uniforms: Partial<AlphaThresholdUniforms>): void;
}

export interface AlphaThresholdMaterialOptions {
  name?: string;
  passIndex?: number;
}

export function createAlphaThresholdMaterial(scene: BABYLON.Scene, options: AlphaThresholdMaterialOptions = {}): AlphaThresholdMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for AlphaThreshold. Expected 0 <= passIndex < 1.`);
  }
  const baseName = options.name ?? 'AlphaThresholdMaterial';
  const shaderName = `${baseName}_pass${passIndex}`;
  // Register shaders in the WGSL store to enable preprocessor
  const vertexShaderName = `${shaderName}VertexShader`;
  const fragmentShaderName = `${shaderName}FragmentShader`;
  
  BABYLON.ShaderStore.ShadersStoreWGSL[vertexShaderName] = AlphaThresholdVertexSource;
  BABYLON.ShaderStore.ShadersStoreWGSL[fragmentShaderName] = AlphaThresholdFragmentSources[passIndex];
  
  const material = new BABYLON.ShaderMaterial(shaderName, scene, {
    vertex: shaderName,
    fragment: shaderName,
  }, {
    attributes: ['position', 'uv'],
    uniforms: ['uniforms_threshold'],
    samplers: ['src'],
    samplerObjects: ['srcSampler'],
    shaderLanguage: BABYLON.ShaderLanguage.WGSL,
  });

  const samplerLookup = { 'src': 'srcSampler' } as const;

  const handles: AlphaThresholdMaterialHandles = {
    material,
    setTexture: (name, texture) => material.setTexture(name, texture),
    setTextureSampler: (name, sampler) => material.setTextureSampler(samplerLookup[name], sampler),
    setUniforms: (values) => setAlphaThresholdUniforms(material, values),
  };

  return handles;
}

export class AlphaThresholdEffect extends CustomShaderEffect<AlphaThresholdUniforms, AlphaThresholdInputs> {
  effectName = 'AlphaThreshold'

  constructor(engine: BABYLON.WebGPUEngine, inputs: AlphaThresholdInputs, width = 1280, height = 720, sampleMode: 'nearest' | 'linear' = 'linear', precision: RenderPrecision = 'half_float') {
    super(engine, inputs, {
      factory: (sceneRef, options) => createAlphaThresholdMaterial(sceneRef, options),
      textureInputKeys: ['src'],
      textureBindingKeys: ['src'],
      passTextureSources: AlphaThresholdPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      materialName: 'AlphaThresholdMaterial',
      sampleMode,
      precision,
      uniformMeta: AlphaThresholdUniformMeta,
    })
  }

  override setSrcs(inputs: Partial<AlphaThresholdInputs>): void {
    super.setSrcs(inputs);
  }

  override setUniforms(uniforms: { threshold?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.threshold !== undefined) {
      record['threshold'] = uniforms.threshold;
    }
    super.setUniforms(record);
  }
}

