// Auto-generated by wgsl fragment generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';
import { CustomShaderEffect, type ShaderSource, type RenderPrecision, type UniformDescriptor, type ShaderUniforms, type Dynamic } from '../shaderFXBabylon';
export const InputCropVertexSource = `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
attribute position: vec3<f32>;
attribute uv: vec2<f32>;
varying vUV: vec2<f32>;

#define CUSTOM_VERTEX_DEFINITIONS
@vertex
fn main(input : VertexInputs) -> FragmentInputs {
#define CUSTOM_VERTEX_MAIN_BEGIN
  vertexOutputs.position = vec4<f32>(vertexInputs.position, 1.0);
  vertexOutputs.vUV = vertexInputs.uv;
#define CUSTOM_VERTEX_MAIN_END
}

`;
export const InputCropFragmentSources = [
  `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
varying vUV: vec2<f32>;
uniform uniforms_origin: vec2f;
uniform uniforms_size: vec2f;
var src: texture_2d<f32>;
var srcSampler: sampler;

// Source fragment function
struct InputCropUniforms {
  origin: vec2f,
  size: vec2f,
};

fn pass0(uv: vec2f, uniforms: InputCropUniforms, src: texture_2d<f32>, srcSampler: sampler) -> vec4f {
  // Map origin from p5's Y-down into texture Y-up: flip origin and keep uv as-is.
  let originFlipped = vec2f(uniforms.origin.x, 1.0 - uniforms.origin.y - uniforms.size.y);
  let sampleUv = originFlipped + uv * uniforms.size;
  let uvClamped = clamp(sampleUv, vec2f(0.0, 0.0), vec2f(1.0, 1.0));

  // mask is 1 when inside [0,1] range, else 0; keeps control flow uniform
  let maskX = step(0.0, sampleUv.x) * step(sampleUv.x, 1.0);
  let maskY = step(0.0, sampleUv.y) * step(sampleUv.y, 1.0);
  let mask = maskX * maskY;

  let color = textureSample(src, srcSampler, uvClamped);
  return vec4f(color.rgb * mask, color.a * mask);
}

fn load_InputCropUniforms() -> InputCropUniforms {
  return InputCropUniforms(
  uniforms.uniforms_origin,
  uniforms.uniforms_size
  );
}

#define CUSTOM_FRAGMENT_DEFINITIONS
@fragment
fn main(input: FragmentInputs) -> FragmentOutputs {
#define CUSTOM_FRAGMENT_MAIN_BEGIN
  let uniforms_value = load_InputCropUniforms();
  let uv_local = fragmentInputs.vUV;
  let color = pass0(uv_local, uniforms_value, src, srcSampler);
  fragmentOutputs.color = color;
#define CUSTOM_FRAGMENT_MAIN_END
}

`, // pass0
] as const;
export const InputCropPassCount = 1 as const;
export const InputCropPrimaryTextureName = 'src' as const;

export const InputCropPassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const InputCropUniformMeta: UniformDescriptor[] = [
  {
    name: 'origin',
    kind: 'vec2f',
    bindingName: 'uniforms_origin',
  },
  {
    name: 'size',
    kind: 'vec2f',
    bindingName: 'uniforms_size',
  },
];

function ensureVector2(value: BABYLON.Vector2 | readonly [number, number]): BABYLON.Vector2 {
  return value instanceof BABYLON.Vector2 ? value : BABYLON.Vector2.FromArray(value as readonly [number, number]);
}

export interface InputCropUniforms {
  origin: BABYLON.Vector2 | readonly [number, number];
  size: BABYLON.Vector2 | readonly [number, number];
}

export function setInputCropUniforms(material: BABYLON.ShaderMaterial, uniforms: Partial<InputCropUniforms>): void {
  if (!uniforms) {
    return;
  }
  if (uniforms.origin !== undefined) {
    material.setVector2('uniforms_origin', ensureVector2(uniforms.origin));
  }
  if (uniforms.size !== undefined) {
    material.setVector2('uniforms_size', ensureVector2(uniforms.size));
  }
}

export type InputCropTextureName = 'src';
export interface InputCropInputs {
  src: ShaderSource;
}

export interface InputCropMaterialHandles {
  material: BABYLON.ShaderMaterial;
  setTexture(name: InputCropTextureName, texture: BABYLON.BaseTexture): void;
  setTextureSampler(name: InputCropTextureName, sampler: BABYLON.TextureSampler): void;
  setUniforms(uniforms: Partial<InputCropUniforms>): void;
}

export interface InputCropMaterialOptions {
  name?: string;
  passIndex?: number;
}

export function createInputCropMaterial(scene: BABYLON.Scene, options: InputCropMaterialOptions = {}): InputCropMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for InputCrop. Expected 0 <= passIndex < 1.`);
  }
  const baseName = options.name ?? 'InputCropMaterial';
  const shaderName = `${baseName}_pass${passIndex}`;
  // Register shaders in the WGSL store to enable preprocessor
  const vertexShaderName = `${shaderName}VertexShader`;
  const fragmentShaderName = `${shaderName}FragmentShader`;
  
  BABYLON.ShaderStore.ShadersStoreWGSL[vertexShaderName] = InputCropVertexSource;
  BABYLON.ShaderStore.ShadersStoreWGSL[fragmentShaderName] = InputCropFragmentSources[passIndex];
  
  const material = new BABYLON.ShaderMaterial(shaderName, scene, {
    vertex: shaderName,
    fragment: shaderName,
  }, {
    attributes: ['position', 'uv'],
    uniforms: ['uniforms_origin', 'uniforms_size'],
    samplers: ['src'],
    samplerObjects: ['srcSampler'],
    shaderLanguage: BABYLON.ShaderLanguage.WGSL,
  });

  const samplerLookup = { 'src': 'srcSampler' } as const;

  const handles: InputCropMaterialHandles = {
    material,
    setTexture: (name, texture) => material.setTexture(name, texture),
    setTextureSampler: (name, sampler) => material.setTextureSampler(samplerLookup[name], sampler),
    setUniforms: (values) => setInputCropUniforms(material, values),
  };

  return handles;
}

export class InputCropEffect extends CustomShaderEffect<InputCropUniforms, InputCropInputs> {
  effectName = 'InputCrop'

  constructor(engine: BABYLON.WebGPUEngine, inputs: InputCropInputs, width = 1280, height = 720, sampleMode: 'nearest' | 'linear' = 'linear', precision: RenderPrecision = 'half_float') {
    super(engine, inputs, {
      factory: (sceneRef, options) => createInputCropMaterial(sceneRef, options),
      textureInputKeys: ['src'],
      textureBindingKeys: ['src'],
      passTextureSources: InputCropPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      materialName: 'InputCropMaterial',
      sampleMode,
      precision,
      uniformMeta: InputCropUniformMeta,
    })
  }

  override setSrcs(inputs: Partial<InputCropInputs>): void {
    super.setSrcs(inputs);
  }

  override setUniforms(uniforms: { origin?: Dynamic<BABYLON.Vector2 | readonly [number, number]>, size?: Dynamic<BABYLON.Vector2 | readonly [number, number]> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.origin !== undefined) {
      record['origin'] = uniforms.origin;
    }
    if (uniforms.size !== undefined) {
      record['size'] = uniforms.size;
    }
    super.setUniforms(record);
  }
}

