// Auto-generated by wgsl fragment generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';
import { CustomShaderEffect, type ShaderInputs } from '../shaderFXBabylon';
export const LayerBlendVertexSource = `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
attribute position: vec3<f32>;
attribute uv: vec2<f32>;
varying vUV: vec2<f32>;
var src1: texture_2d<f32>;
var src1Sampler: sampler;
var src2: texture_2d<f32>;
var src2Sampler: sampler;

#define CUSTOM_VERTEX_DEFINITIONS
@vertex
fn main(input : VertexInputs) -> FragmentInputs {
#define CUSTOM_VERTEX_MAIN_BEGIN
  vertexOutputs.position = vec4<f32>(vertexInputs.position, 1.0);
  vertexOutputs.vUV = vertexInputs.uv;
#define CUSTOM_VERTEX_MAIN_END
}

`;
export const LayerBlendFragmentSource = `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
varying vUV: vec2<f32>;
var src1: texture_2d<f32>;
var src1Sampler: sampler;
var src2: texture_2d<f32>;
var src2Sampler: sampler;

// Source fragment function
fn layerBlend(uv: vec2f, src1: texture_2d<f32>, src1Sampler: sampler, src2: texture_2d<f32>, src2Sampler: sampler) -> vec4f {
  let color1 = textureSample(src1, src1Sampler, uv);
  let color2 = textureSample(src2, src2Sampler, uv);
  // Proper alpha composite of src2 over src1
  let returnColor = color1 * (1.0 - color2.a) + color2;
  return returnColor;
}

#define CUSTOM_FRAGMENT_DEFINITIONS
@fragment
fn main(input: FragmentInputs) -> FragmentOutputs {
#define CUSTOM_FRAGMENT_MAIN_BEGIN
  let uv_local = fragmentInputs.vUV;
  let color = layerBlend(uv_local, src1, src1Sampler, src2, src2Sampler);
  fragmentOutputs.color = color;
#define CUSTOM_FRAGMENT_MAIN_END
}

`;

export type LayerBlendUniforms = Record<string, never>;
export function setLayerBlendUniforms(_material: BABYLON.ShaderMaterial, _uniforms: Partial<LayerBlendUniforms>): void {}

export type LayerBlendTextureName = 'src1' | 'src2';
export interface LayerBlendMaterialHandles {
  material: BABYLON.ShaderMaterial;
  setTexture(name: LayerBlendTextureName, texture: BABYLON.BaseTexture): void;
  setTextureSampler(name: LayerBlendTextureName, sampler: BABYLON.TextureSampler): void;
  setUniforms(uniforms: Partial<LayerBlendUniforms>): void;
}

export interface LayerBlendMaterialOptions {
  name?: string;
}

export function createLayerBlendMaterial(scene: BABYLON.Scene, options: LayerBlendMaterialOptions = {}): LayerBlendMaterialHandles {
  const name = options.name ?? 'LayerBlendMaterial';
  // Register shaders in the WGSL store to enable preprocessor
  const vertexShaderName = `${name}VertexShader`;
  const fragmentShaderName = `${name}FragmentShader`;
  
  BABYLON.ShaderStore.ShadersStoreWGSL[vertexShaderName] = LayerBlendVertexSource;
  BABYLON.ShaderStore.ShadersStoreWGSL[fragmentShaderName] = LayerBlendFragmentSource;
  
  const material = new BABYLON.ShaderMaterial(name, scene, {
    vertex: name,
    fragment: name,
  }, {
    attributes: ['position', 'uv'],
    uniforms: [],
    samplers: ['src1', 'src2'],
    samplerObjects: ['src1Sampler', 'src2Sampler'],
    shaderLanguage: BABYLON.ShaderLanguage.WGSL,
  });

  const samplerLookup = { 'src1': 'src1Sampler', 'src2': 'src2Sampler' } as const;

  const handles: LayerBlendMaterialHandles = {
    material,
    setTexture: (name, texture) => material.setTexture(name, texture),
    setTextureSampler: (name, sampler) => material.setTextureSampler(samplerLookup[name], sampler),
    setUniforms: () => {},
  };

  return handles;
}

export class LayerBlendEffect extends CustomShaderEffect<LayerBlendUniforms> {
  effectName = 'LayerBlend'

  constructor(engine: BABYLON.WebGPUEngine, inputs: ShaderInputs, width = 1280, height = 720, sampleMode: 'nearest' | 'linear' = 'linear') {
    super(engine, inputs, {
      factory: (sceneRef, options) => createLayerBlendMaterial(sceneRef, options),
      textureInputKeys: ['src1', 'src2'],
      width,
      height,
      materialName: 'LayerBlendMaterial',
      sampleMode,
    })
  }
}

