// Auto-generated by wgsl fragment generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';
import { CustomShaderEffect, type ShaderSource, type RenderPrecision, type UniformDescriptor, type ShaderUniforms, type Dynamic } from '../shaderFXBabylon';
export const PolygonMaskVertexSource = `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
attribute position: vec3<f32>;
attribute uv: vec2<f32>;
varying vUV: vec2<f32>;

#define CUSTOM_VERTEX_DEFINITIONS
@vertex
fn main(input : VertexInputs) -> FragmentInputs {
#define CUSTOM_VERTEX_MAIN_BEGIN
  vertexOutputs.position = vec4<f32>(vertexInputs.position, 1.0);
  vertexOutputs.vUV = vertexInputs.uv;
#define CUSTOM_VERTEX_MAIN_END
}

`;
export const PolygonMaskFragmentSources = [
  `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
varying vUV: vec2<f32>;
uniform uniforms_points: array<vec2f, 64>;
uniform uniforms_pointCount: i32;
var src: texture_2d<f32>;
var srcSampler: sampler;

// Source fragment function
struct PolygonMaskUniforms {
  points: array<vec2f, 64>,
  pointCount: i32,
};

fn pointInPolygon(pt: vec2f, uniforms: PolygonMaskUniforms) -> bool {
  let count = uniforms.pointCount;
  if (count < 3) {
    return true;
  }

  var inside = false;
  var j = count - 1;

  for (var i = 0; i < 64; i = i + 1) {
    if (i >= count) {
      break;
    }
    let pi = uniforms.points[u32(i)];
    let pj = uniforms.points[u32(j)];
    let intersects = (pi.y > pt.y) != (pj.y > pt.y);
    if (intersects) {
      let xCross = (pj.x - pi.x) * (pt.y - pi.y) / (pj.y - pi.y) + pi.x;
      if (pt.x < xCross) {
        inside = !inside;
      }
    }
    j = i;
  }

  return inside;
}

fn pass0(uv: vec2f, uniforms: PolygonMaskUniforms, src: texture_2d<f32>, srcSampler: sampler) -> vec4f {
  let color = textureSample(src, srcSampler, uv);
  if (!pointInPolygon(uv, uniforms)) {
    return vec4f(0.0, 0.0, 0.0, 0.0);
  }
  return color;
}

fn load_PolygonMaskUniforms() -> PolygonMaskUniforms {
  var result: PolygonMaskUniforms;
  result.points = uniforms.uniforms_points;
  result.pointCount = uniforms.uniforms_pointCount;
  return result;
}

#define CUSTOM_FRAGMENT_DEFINITIONS
@fragment
fn main(input: FragmentInputs) -> FragmentOutputs {
#define CUSTOM_FRAGMENT_MAIN_BEGIN
  let uniforms_value = load_PolygonMaskUniforms();
  let uv_local = fragmentInputs.vUV;
  let color = pass0(uv_local, uniforms_value, src, srcSampler);
  fragmentOutputs.color = color;
#define CUSTOM_FRAGMENT_MAIN_END
}

`, // pass0
] as const;
export const PolygonMaskPassCount = 1 as const;
export const PolygonMaskPrimaryTextureName = 'src' as const;

export const PolygonMaskPassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const PolygonMaskUniformMeta: UniformDescriptor[] = [
  {
    name: 'points',
    kind: 'vec2f',
    isArray: true,
    arraySize: 64,
    bindingName: 'uniforms_points',
  },
  {
    name: 'pointCount',
    kind: 'i32',
    bindingName: 'uniforms_pointCount',
  },
];

export interface Vec2Like { x: number; y: number }
export interface Vec3Like { x: number; y: number; z: number }
export interface Vec4Like { x: number; y: number; z: number; w: number }

function packVec2Array(arr: Vec2Like[]): number[] {
  return arr.flatMap(v => [v.x, v.y]);
}

export interface PolygonMaskUniforms {
  points: Vec2Like[];
  pointCount: number;
}

export function setPolygonMaskUniforms(material: BABYLON.ShaderMaterial, uniforms: Partial<PolygonMaskUniforms>): void {
  if (!uniforms) {
    return;
  }
  if (uniforms.points !== undefined) {
    material.setArray2('uniforms_points', packVec2Array(uniforms.points));
  }
  if (uniforms.pointCount !== undefined) {
    material.setInt('uniforms_pointCount', uniforms.pointCount);
  }
}

export type PolygonMaskTextureName = 'src';
export interface PolygonMaskInputs {
  src: ShaderSource;
}

export interface PolygonMaskMaterialHandles {
  material: BABYLON.ShaderMaterial;
  setTexture(name: PolygonMaskTextureName, texture: BABYLON.BaseTexture): void;
  setTextureSampler(name: PolygonMaskTextureName, sampler: BABYLON.TextureSampler): void;
  setUniforms(uniforms: Partial<PolygonMaskUniforms>): void;
}

export interface PolygonMaskMaterialOptions {
  name?: string;
  passIndex?: number;
}

export function createPolygonMaskMaterial(scene: BABYLON.Scene, options: PolygonMaskMaterialOptions = {}): PolygonMaskMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for PolygonMask. Expected 0 <= passIndex < 1.`);
  }
  const baseName = options.name ?? 'PolygonMaskMaterial';
  const shaderName = `${baseName}_pass${passIndex}`;
  // Register shaders in the WGSL store to enable preprocessor
  const vertexShaderName = `${shaderName}VertexShader`;
  const fragmentShaderName = `${shaderName}FragmentShader`;
  
  BABYLON.ShaderStore.ShadersStoreWGSL[vertexShaderName] = PolygonMaskVertexSource;
  BABYLON.ShaderStore.ShadersStoreWGSL[fragmentShaderName] = PolygonMaskFragmentSources[passIndex];
  
  const material = new BABYLON.ShaderMaterial(shaderName, scene, {
    vertex: shaderName,
    fragment: shaderName,
  }, {
    attributes: ['position', 'uv'],
    uniforms: ['uniforms_points', 'uniforms_pointCount'],
    samplers: ['src'],
    samplerObjects: ['srcSampler'],
    shaderLanguage: BABYLON.ShaderLanguage.WGSL,
  });

  const samplerLookup = { 'src': 'srcSampler' } as const;

  const handles: PolygonMaskMaterialHandles = {
    material,
    setTexture: (name, texture) => material.setTexture(name, texture),
    setTextureSampler: (name, sampler) => material.setTextureSampler(samplerLookup[name], sampler),
    setUniforms: (values) => setPolygonMaskUniforms(material, values),
  };

  return handles;
}

export class PolygonMaskEffect extends CustomShaderEffect<PolygonMaskUniforms, PolygonMaskInputs> {
  effectName = 'PolygonMask'

  constructor(engine: BABYLON.WebGPUEngine, inputs: PolygonMaskInputs, width = 1280, height = 720, sampleMode: 'nearest' | 'linear' = 'linear', precision: RenderPrecision = 'half_float') {
    super(engine, inputs, {
      factory: (sceneRef, options) => createPolygonMaskMaterial(sceneRef, options),
      textureInputKeys: ['src'],
      textureBindingKeys: ['src'],
      passTextureSources: PolygonMaskPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      materialName: 'PolygonMaskMaterial',
      sampleMode,
      precision,
      uniformMeta: PolygonMaskUniformMeta,
    })
  }

  override setSrcs(inputs: Partial<PolygonMaskInputs>): void {
    super.setSrcs(inputs);
  }

  override setUniforms(uniforms: { points?: Dynamic<Vec2Like[]>, pointCount?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.points !== undefined) {
      record['points'] = uniforms.points;
    }
    if (uniforms.pointCount !== undefined) {
      record['pointCount'] = uniforms.pointCount;
    }
    super.setUniforms(record);
  }
}

