// Auto-generated by power2d glsl stroke material generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';

export const BasicVertexSource = `// Auto-generated by power2d glsl stroke material generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec3 position;
in vec2 uv;
in vec2 strokeNormal;
in float strokeSide;
in float strokeArcLength;
in float strokeNormalizedArc;
in float strokeMiterFactor;
out vec2 vUV;
out float vArcLength;
out float vNormalizedArc;
uniform vec3 uniforms_color;
uniform vec2 power2d_shapeTranslate;
uniform float power2d_shapeRotation;
uniform vec2 power2d_shapeScale;
uniform float power2d_canvasWidth;
uniform float power2d_canvasHeight;
uniform float power2d_strokeThickness;

struct BasicStrokeUniforms {
  vec3 color;
};

vec2 strokeVertShader(
  vec2 centerPos,
  vec2 normal,
  float side,
  float arcLength,
  float normalizedArc,
  float miterFactor,
  float thickness,
  BasicStrokeUniforms uniforms
) {
  return centerPos + normal * side * (thickness * 0.5) * miterFactor;
}

vec4 strokeFragShader(
  vec2 uv,
  float arcLength,
  float normalizedArc,
  BasicStrokeUniforms uniforms
) {
  return vec4(uniforms.color, 1.0);
}


BasicStrokeUniforms load_BasicStrokeUniforms() {
  return BasicStrokeUniforms(
    uniforms_color
  );
}

vec2 power2d_applyShapeTransform(vec2 pixel) {
  vec2 scaled = pixel * power2d_shapeScale;
  float s = sin(power2d_shapeRotation);
  float c = cos(power2d_shapeRotation);
  vec2 rotated = vec2(
    scaled.x * c - scaled.y * s,
    scaled.x * s + scaled.y * c
  );
  return rotated + power2d_shapeTranslate;
}

vec4 power2d_pixelToNDC(vec2 pixel) {
  float ndcX = (pixel.x / power2d_canvasWidth) * 2.0 - 1.0;
  float ndcY = -((pixel.y / power2d_canvasHeight) * 2.0 - 1.0);
  return vec4(ndcX, ndcY, 0.0, 1.0);
}

void main() {
  BasicStrokeUniforms uniformsValue = load_BasicStrokeUniforms();
  vec2 centerPos = vec2(position.x, position.y);
  vec2 normal = strokeNormal;
  float side = strokeSide;
  float arcLength = strokeArcLength;
  float normalizedArc = strokeNormalizedArc;
  float miterFactor = strokeMiterFactor;
  float thickness = power2d_strokeThickness;
  vec2 uvLocal = uv;
  vec2 adjustedPixelPos = strokeVertShader(centerPos, normal, side, arcLength, normalizedArc, miterFactor, thickness, uniformsValue);
  vec2 transformedPixelPos = power2d_applyShapeTransform(adjustedPixelPos);
  gl_Position = power2d_pixelToNDC(transformedPixelPos);
  vUV = uvLocal;
  vArcLength = arcLength;
  vNormalizedArc = normalizedArc;
}`;
export const BasicFragmentSource = `// Auto-generated by power2d glsl stroke material generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec2 vUV;
in float vArcLength;
in float vNormalizedArc;
out vec4 outColor;
uniform vec3 uniforms_color;
uniform vec2 power2d_shapeTranslate;
uniform float power2d_shapeRotation;
uniform vec2 power2d_shapeScale;
uniform float power2d_canvasWidth;
uniform float power2d_canvasHeight;
uniform float power2d_strokeThickness;

struct BasicStrokeUniforms {
  vec3 color;
};

vec2 strokeVertShader(
  vec2 centerPos,
  vec2 normal,
  float side,
  float arcLength,
  float normalizedArc,
  float miterFactor,
  float thickness,
  BasicStrokeUniforms uniforms
) {
  return centerPos + normal * side * (thickness * 0.5) * miterFactor;
}

vec4 strokeFragShader(
  vec2 uv,
  float arcLength,
  float normalizedArc,
  BasicStrokeUniforms uniforms
) {
  return vec4(uniforms.color, 1.0);
}


BasicStrokeUniforms load_BasicStrokeUniforms() {
  return BasicStrokeUniforms(
    uniforms_color
  );
}

void main() {
  BasicStrokeUniforms uniformsValue = load_BasicStrokeUniforms();
  vec2 uvLocal = vUV;
  float arcLength = vArcLength;
  float normalizedArc = vNormalizedArc;
  vec4 color = strokeFragShader(uvLocal, arcLength, normalizedArc, uniformsValue);
  outColor = color;
}`;

function ensureVector3(value: BABYLON.Vector3 | readonly [number, number, number]): BABYLON.Vector3 {
  return value instanceof BABYLON.Vector3 ? value : BABYLON.Vector3.FromArray(value as readonly [number, number, number]);
}

export interface BasicUniforms {
  color: BABYLON.Vector3 | readonly [number, number, number];
}

export const BasicUniformDefaults: BasicUniforms = {
  color: [0, 0, 0],
};

export const BasicUniformMeta = [
  {
    name: 'color',
    kind: 'vec3f',
    bindingName: 'uniforms_color',
  },
] as const;

export function setBasicUniforms(material: BABYLON.ShaderMaterial, uniforms: Partial<BasicUniforms>): void {
  if (!uniforms) {
    return;
  }
  if (uniforms.color !== undefined) {
    material.setVector3('uniforms_color', ensureVector3(uniforms.color));
  }
}

export type BasicTextureName = never;
export const BasicTextureNames = [] as const;

export interface BasicStrokeMaterialDef {
  readonly uniformType: BasicUniforms;
  readonly textureNames: readonly BasicTextureName[];
  readonly vertexSource: string;
  readonly fragmentSource: string;
  readonly uniformMeta: typeof BasicUniformMeta;
  readonly uniformDefaults: BasicUniforms;
  readonly createMaterial: (scene: BABYLON.Scene, name?: string) => BasicStrokeMaterialInstance;
}

export interface BasicStrokeMaterialInstance {
  material: BABYLON.ShaderMaterial;
  setUniforms(uniforms: Partial<BasicUniforms>): void;
  setTexture(name: BasicTextureName, texture: BABYLON.BaseTexture): void;
  setCanvasSize(width: number, height: number): void;
  dispose(): void;
}

export function createBasicStrokeMaterial(scene: BABYLON.Scene, name: string = 'BasicStrokeMaterial'): BasicStrokeMaterialInstance {
  const vertexShaderName = `${name}VertexShader`;
  const fragmentShaderName = `${name}FragmentShader`;

  BABYLON.ShaderStore.ShadersStore[vertexShaderName] = BasicVertexSource;
  BABYLON.ShaderStore.ShadersStore[fragmentShaderName] = BasicFragmentSource;

  const material = new BABYLON.ShaderMaterial(name, scene, {
    vertex: name,
    fragment: name,
  }, {
    attributes: ["position","uv","strokeNormal","strokeSide","strokeArcLength","strokeNormalizedArc","strokeMiterFactor"],
    uniforms: ["uniforms_color","power2d_shapeTranslate","power2d_shapeRotation","power2d_shapeScale","power2d_canvasWidth","power2d_canvasHeight","power2d_strokeThickness"],
    samplers: [],
    shaderLanguage: BABYLON.ShaderLanguage.GLSL,
  });

  setBasicUniforms(material, BasicUniformDefaults);
  material.setVector2('power2d_shapeTranslate', new BABYLON.Vector2(0, 0));
  material.setFloat('power2d_shapeRotation', 0);
  material.setVector2('power2d_shapeScale', new BABYLON.Vector2(1, 1));
  material.setFloat('power2d_strokeThickness', 1);
  material.disableDepthWrite = true;
  material.depthFunction = BABYLON.Constants.ALWAYS;
  material.backFaceCulling = false;
  material.alphaMode = BABYLON.Engine.ALPHA_COMBINE;

  const handles: BasicStrokeMaterialInstance = {
    material,
    setUniforms: (uniforms) => setBasicUniforms(material, uniforms),
    setTexture: (name, texture) => material.setTexture(name, texture),
    setCanvasSize: (width, height) => {
      material.setFloat('power2d_canvasWidth', width);
      material.setFloat('power2d_canvasHeight', height);
    },
    dispose: () => {
      material.dispose(true, false);
      delete BABYLON.ShaderStore.ShadersStore[vertexShaderName];
      delete BABYLON.ShaderStore.ShadersStore[fragmentShaderName];
    },
  };

  return handles;
}

export const BasicStrokeMaterial: BasicStrokeMaterialDef = {
  uniformType: undefined as unknown as BasicUniforms,
  textureNames: BasicTextureNames,
  vertexSource: BasicVertexSource,
  fragmentSource: BasicFragmentSource,
  uniformMeta: BasicUniformMeta,
  uniformDefaults: BasicUniformDefaults,
  createMaterial: createBasicStrokeMaterial,
};

export const BasicMaterial: BasicStrokeMaterialDef = BasicStrokeMaterial;

export default BasicStrokeMaterial;