// Auto-generated by power2d glsl material generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';

export const BasicVertexSource = `// Auto-generated by power2d glsl material generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec3 position;
in vec2 uv;
out vec2 vUV;
uniform float uniforms_time;
uniform vec3 uniforms_color;
uniform vec2 power2d_shapeTranslate;
uniform float power2d_shapeRotation;
uniform vec2 power2d_shapeScale;
uniform float power2d_canvasWidth;
uniform float power2d_canvasHeight;

struct BasicUniforms {
  float time;
  vec3 color;
};

vec2 vertShader(vec2 position, vec2 uv, BasicUniforms uniforms) {
  float wobble = sin((uv.x + uv.y + uniforms.time) * 6.283) * 2.0;
  return position + vec2(wobble, wobble);
}

vec4 fragShader(vec2 uv, BasicUniforms uniforms) {
  float pulse = 0.5 + 0.5 * sin(uniforms.time * 2.0 + uv.x * 3.14159);
  return vec4(uniforms.color * pulse, 1.0);
}

// Uniform helpers

BasicUniforms load_BasicUniforms() {
  return BasicUniforms(
    uniforms_time,
    uniforms_color
  );
}

vec2 power2d_applyShapeTransform(vec2 pixel) {
  vec2 scaled = pixel * power2d_shapeScale;
  float s = sin(power2d_shapeRotation);
  float c = cos(power2d_shapeRotation);
  vec2 rotated = vec2(
    scaled.x * c - scaled.y * s,
    scaled.x * s + scaled.y * c
  );
  return rotated + power2d_shapeTranslate;
}

vec4 power2d_pixelToNDC(vec2 pixel) {
  float ndcX = (pixel.x / power2d_canvasWidth) * 2.0 - 1.0;
  float ndcY = -((pixel.y / power2d_canvasHeight) * 2.0 - 1.0);
  return vec4(ndcX, ndcY, 0.0, 1.0);
}

void main() {
  BasicUniforms uniformsValue = load_BasicUniforms();
  vec2 pixelPos = vec2(position.x, position.y);
  vec2 uvLocal = uv;
  vec2 adjustedPixelPos = vertShader(pixelPos, uvLocal, uniformsValue);
  vec2 transformedPixelPos = power2d_applyShapeTransform(adjustedPixelPos);
  gl_Position = power2d_pixelToNDC(transformedPixelPos);
  vUV = uvLocal;
}`;
export const BasicFragmentSource = `// Auto-generated by power2d glsl material generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec2 vUV;
out vec4 outColor;
uniform float uniforms_time;
uniform vec3 uniforms_color;
uniform vec2 power2d_shapeTranslate;
uniform float power2d_shapeRotation;
uniform vec2 power2d_shapeScale;
uniform float power2d_canvasWidth;
uniform float power2d_canvasHeight;

struct BasicUniforms {
  float time;
  vec3 color;
};

vec2 vertShader(vec2 position, vec2 uv, BasicUniforms uniforms) {
  float wobble = sin((uv.x + uv.y + uniforms.time) * 6.283) * 2.0;
  return position + vec2(wobble, wobble);
}

vec4 fragShader(vec2 uv, BasicUniforms uniforms) {
  float pulse = 0.5 + 0.5 * sin(uniforms.time * 2.0 + uv.x * 3.14159);
  return vec4(uniforms.color * pulse, 1.0);
}


BasicUniforms load_BasicUniforms() {
  return BasicUniforms(
    uniforms_time,
    uniforms_color
  );
}

void main() {
  vec2 uvLocal = vUV;
  BasicUniforms uniformsValue = load_BasicUniforms();
  vec4 color = fragShader(uvLocal, uniformsValue);
  outColor = color;
}`;

function ensureVector3(value: BABYLON.Vector3 | readonly [number, number, number]): BABYLON.Vector3 {
  return value instanceof BABYLON.Vector3 ? value : BABYLON.Vector3.FromArray(value as readonly [number, number, number]);
}

export interface BasicUniforms {
  time: number;
  color: BABYLON.Vector3 | readonly [number, number, number];
}

export const BasicUniformDefaults: BasicUniforms = {
  time: 0,
  color: [0, 0, 0],
};

export const BasicUniformMeta = [
  {
    name: 'time',
    kind: 'f32',
    bindingName: 'uniforms_time',
  },
  {
    name: 'color',
    kind: 'vec3f',
    bindingName: 'uniforms_color',
  },
] as const;

export function setBasicUniforms(material: BABYLON.ShaderMaterial, uniforms: Partial<BasicUniforms>): void {
  if (!uniforms) {
    return;
  }
  if (uniforms.time !== undefined) {
    material.setFloat('uniforms_time', uniforms.time);
  }
  if (uniforms.color !== undefined) {
    material.setVector3('uniforms_color', ensureVector3(uniforms.color));
  }
}

export type BasicTextureName = never;
export const BasicTextureNames = [] as const;

export interface BasicMaterialDef {
  readonly uniformType: BasicUniforms;
  readonly textureNames: readonly BasicTextureName[];
  readonly vertexSource: string;
  readonly fragmentSource: string;
  readonly uniformMeta: typeof BasicUniformMeta;
  readonly uniformDefaults: BasicUniforms;
  readonly createMaterial: (scene: BABYLON.Scene, name?: string) => BasicMaterialInstance;
}

export interface BasicMaterialInstance {
  material: BABYLON.ShaderMaterial;
  setUniforms(uniforms: Partial<BasicUniforms>): void;
  setTexture(name: BasicTextureName, texture: BABYLON.BaseTexture): void;
  setCanvasSize(width: number, height: number): void;
  dispose(): void;
}

export function createBasicMaterial(scene: BABYLON.Scene, name: string = 'BasicMaterial'): BasicMaterialInstance {
  const vertexShaderName = `${name}VertexShader`;
  const fragmentShaderName = `${name}FragmentShader`;

  BABYLON.ShaderStore.ShadersStore[vertexShaderName] = BasicVertexSource;
  BABYLON.ShaderStore.ShadersStore[fragmentShaderName] = BasicFragmentSource;

  const material = new BABYLON.ShaderMaterial(name, scene, {
    vertex: name,
    fragment: name,
  }, {
    attributes: ["position","uv"],
    uniforms: ["uniforms_time","uniforms_color","power2d_shapeTranslate","power2d_shapeRotation","power2d_shapeScale","power2d_canvasWidth","power2d_canvasHeight"],
    samplers: [],
    shaderLanguage: BABYLON.ShaderLanguage.GLSL,
  });

  setBasicUniforms(material, BasicUniformDefaults);
  material.setVector2('power2d_shapeTranslate', new BABYLON.Vector2(0, 0));
  material.setFloat('power2d_shapeRotation', 0);
  material.setVector2('power2d_shapeScale', new BABYLON.Vector2(1, 1));
  material.disableDepthWrite = true;
  material.depthFunction = BABYLON.Constants.ALWAYS;
  material.backFaceCulling = false;
  material.alphaMode = BABYLON.Engine.ALPHA_COMBINE;

  const handles: BasicMaterialInstance = {
    material,
    setUniforms: (uniforms) => setBasicUniforms(material, uniforms),
    setTexture: (name, texture) => material.setTexture(name, texture),
    setCanvasSize: (width, height) => {
      material.setFloat('power2d_canvasWidth', width);
      material.setFloat('power2d_canvasHeight', height);
    },
    dispose: () => {
      material.dispose(true, false);
      delete BABYLON.ShaderStore.ShadersStore[vertexShaderName];
      delete BABYLON.ShaderStore.ShadersStore[fragmentShaderName];
    },
  };

  return handles;
}

export const BasicMaterial: BasicMaterialDef = {
  uniformType: undefined as unknown as BasicUniforms,
  textureNames: BasicTextureNames,
  vertexSource: BasicVertexSource,
  fragmentSource: BasicFragmentSource,
  uniformMeta: BasicUniformMeta,
  uniformDefaults: BasicUniformDefaults,
  createMaterial: createBasicMaterial,
};

export default BasicMaterial;