// Auto-generated by glsl fragment generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';
import { CustomShaderEffect, type ShaderSource, type RenderPrecision, type UniformDescriptor, type ShaderUniforms, type Dynamic } from '../shaderFXBabylon_GL';
export const HorizontalBlurVertexSource = `// Auto-generated by glsl fragment generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec3 position;
in vec2 uv;
out vec2 vUV;

void main() {
  gl_Position = vec4(position, 1.0);
  vUV = uv;
}`;
export const HorizontalBlurFragmentSources = [
  `// Auto-generated by glsl fragment generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec2 vUV;
out vec4 outColor;
uniform int uniforms_pixels;
uniform float uniforms_resolution;
uniform sampler2D src;

struct HorizontalBlurUniforms {
  int pixels;
  float resolution;
};

vec4 pass0(vec2 uv, HorizontalBlurUniforms uniforms, sampler2D src) {
  if (uniforms.pixels <= 0) {
    return texture(src, uv);
  }

  vec4 color = vec4(0.0);
  float total = 0.0;
  float offset = 1.0 / uniforms.resolution;

  for (int i = -uniforms.pixels; i <= uniforms.pixels; i++) {
    float weight = 1.0 - (abs(float(i)) / float(uniforms.pixels + 1));
    vec2 sampleUV = uv + vec2(offset * float(i), 0.0);
    color += texture(src, sampleUV) * weight;
    total += weight;
  }

  return color / total;
}

HorizontalBlurUniforms load_HorizontalBlurUniforms() {
  HorizontalBlurUniforms result;
  result.pixels = uniforms_pixels;
  result.resolution = uniforms_resolution;
  return result;
}

void main() {
  HorizontalBlurUniforms uniforms_value = load_HorizontalBlurUniforms();
  vec2 uv_local = vUV;
  vec4 color = pass0(uv_local, uniforms_value, src);
  outColor = color;
}`, // pass0
] as const;
export const HorizontalBlurPassCount = 1 as const;
export const HorizontalBlurPrimaryTextureName = 'src' as const;

export const HorizontalBlurPassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const HorizontalBlurUniformMeta: UniformDescriptor[] = [
  {
    name: 'pixels',
    kind: 'i32',
    bindingName: 'uniforms_pixels',
  },
  {
    name: 'resolution',
    kind: 'f32',
    bindingName: 'uniforms_resolution',
  },
];

export interface HorizontalBlurUniforms {
  pixels: number;
  resolution: number;
}

export function setHorizontalBlurUniforms(material: BABYLON.ShaderMaterial, uniforms: Partial<HorizontalBlurUniforms>): void {
  if (!uniforms) {
    return;
  }
  if (uniforms.pixels !== undefined) {
    material.setInt('uniforms_pixels', uniforms.pixels);
  }
  if (uniforms.resolution !== undefined) {
    material.setFloat('uniforms_resolution', uniforms.resolution);
  }
}

export type HorizontalBlurTextureName = 'src';
export interface HorizontalBlurInputs {
  src: ShaderSource;
}

export interface HorizontalBlurMaterialHandles {
  material: BABYLON.ShaderMaterial;
  setTexture(name: HorizontalBlurTextureName, texture: BABYLON.BaseTexture): void;
  setTextureSampler(name: HorizontalBlurTextureName, sampler: BABYLON.TextureSampler): void;
  setUniforms(uniforms: Partial<HorizontalBlurUniforms>): void;
}

export interface HorizontalBlurMaterialOptions {
  name?: string;
  passIndex?: number;
}

export function createHorizontalBlurMaterial(scene: BABYLON.Scene, options: HorizontalBlurMaterialOptions = {}): HorizontalBlurMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error('Invalid passIndex ' + passIndex + ' for HorizontalBlur. Expected 0 <= passIndex < 1.');
  }
  const baseName = options.name ?? 'HorizontalBlurMaterial';
  const shaderName = `${baseName}_pass${passIndex}`;
  const vertexShaderName = `${shaderName}VertexShader`;
  const fragmentShaderName = `${shaderName}FragmentShader`;

  BABYLON.ShaderStore.ShadersStore[vertexShaderName] = HorizontalBlurVertexSource;
  BABYLON.ShaderStore.ShadersStore[fragmentShaderName] = HorizontalBlurFragmentSources[passIndex];

  const material = new BABYLON.ShaderMaterial(shaderName, scene, {
    vertex: shaderName,
    fragment: shaderName,
  }, {
    attributes: ['position', 'uv'],
    uniforms: ['uniforms_pixels', 'uniforms_resolution'],
    samplers: ['src'],
    shaderLanguage: BABYLON.ShaderLanguage.GLSL,
  });

  const defaultSampler = new BABYLON.TextureSampler();
  defaultSampler.setParameters(
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    undefined,
    BABYLON.Texture.BILINEAR_SAMPLINGMODE,
  );
  const samplerState: Record<string, BABYLON.TextureSampler> = {};
  const textureState: Partial<Record<HorizontalBlurTextureName, BABYLON.BaseTexture | null>> = {};
  const applySamplerToTexture = (texture: BABYLON.BaseTexture | null, sampler: BABYLON.TextureSampler) => {
    if (!texture) return;
    const wrapU = sampler.wrapU;
    if (wrapU !== null && wrapU !== undefined) {
      texture.wrapU = wrapU;
    }
    const wrapV = sampler.wrapV;
    if (wrapV !== null && wrapV !== undefined) {
      texture.wrapV = wrapV;
    }
    const wrapR = sampler.wrapR;
    if (wrapR !== null && wrapR !== undefined) {
      texture.wrapR = wrapR;
    }
    texture.updateSamplingMode(sampler.samplingMode);
  };

  const handles: HorizontalBlurMaterialHandles = {
    material,
    setTexture: (name, texture) => {
      material.setTexture(name, texture);
      textureState[name] = texture;
      const sampler = samplerState[name] ?? defaultSampler;
      applySamplerToTexture(texture, sampler);
    },
    setTextureSampler: (name, sampler) => {
      samplerState[name] = sampler;
      const texture = textureState[name] ?? null;
      applySamplerToTexture(texture, sampler);
    },
    setUniforms: (values) => setHorizontalBlurUniforms(material, values),
  };

  return handles;
}

export class HorizontalBlurEffect extends CustomShaderEffect<HorizontalBlurUniforms, HorizontalBlurInputs> {
  effectName = 'HorizontalBlur'

  constructor(engine: BABYLON.Engine, inputs: HorizontalBlurInputs, width = 1280, height = 720, sampleMode: 'nearest' | 'linear' = 'linear', precision: RenderPrecision = 'half_float') {
    super(engine, inputs, {
      factory: (sceneRef, options) => createHorizontalBlurMaterial(sceneRef, options),
      textureInputKeys: ['src'],
      textureBindingKeys: ['src'],
      passTextureSources: HorizontalBlurPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      materialName: 'HorizontalBlurMaterial',
      sampleMode,
      precision,
      uniformMeta: HorizontalBlurUniformMeta,
    });
    this.setUniforms({
    });
  }

  override setSrcs(inputs: Partial<HorizontalBlurInputs>): void {
    super.setSrcs(inputs);
  }

  override setUniforms(uniforms: { pixels?: Dynamic<number>; resolution?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.pixels !== undefined) {
      record['pixels'] = uniforms.pixels;
    }
    if (uniforms.resolution !== undefined) {
      record['resolution'] = uniforms.resolution;
    }
    super.setUniforms(record);
  }
}