// Auto-generated by glsl fragment generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';
import { CustomShaderEffect, type ShaderSource, type RenderPrecision, type UniformDescriptor, type ShaderUniforms, type Dynamic } from '../shaderFXBabylon_GL';
export const LayerBlendVertexSource = `// Auto-generated by glsl fragment generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec3 position;
in vec2 uv;
out vec2 vUV;

void main() {
  gl_Position = vec4(position, 1.0);
  vUV = uv;
}`;
export const LayerBlendFragmentSources = [
  `// Auto-generated by glsl fragment generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec2 vUV;
out vec4 outColor;
uniform sampler2D src1;
uniform sampler2D src2;

vec4 pass0(vec2 uv, sampler2D src1, sampler2D src2) {
  vec4 color1 = texture(src1, uv);
  vec4 color2 = texture(src2, uv);
  return color1.a > 0.01 ? color1 : color2;
}

void main() {
  vec2 uv_local = vUV;
  vec4 color = pass0(uv_local, src1, src2);
  outColor = color;
}`, // pass0
] as const;
export const LayerBlendPassCount = 1 as const;
export const LayerBlendPrimaryTextureName = 'src1' as const;

export const LayerBlendPassTextureSources = [
  [
    { binding: 'src1', source: { kind: 'input', key: 'src1' } },
    { binding: 'src2', source: { kind: 'input', key: 'src2' } },
  ],
] as const;

export const LayerBlendUniformMeta: UniformDescriptor[] = [];

export type LayerBlendUniforms = Record<string, never>;
export function setLayerBlendUniforms(_material: BABYLON.ShaderMaterial, _uniforms: Partial<LayerBlendUniforms>): void { }

export type LayerBlendTextureName = 'src1' | 'src2';
export interface LayerBlendInputs {
  src1: ShaderSource;
  src2: ShaderSource;
}

export interface LayerBlendMaterialHandles {
  material: BABYLON.ShaderMaterial;
  setTexture(name: LayerBlendTextureName, texture: BABYLON.BaseTexture): void;
  setTextureSampler(name: LayerBlendTextureName, sampler: BABYLON.TextureSampler): void;
  setUniforms(uniforms: Partial<LayerBlendUniforms>): void;
}

export interface LayerBlendMaterialOptions {
  name?: string;
  passIndex?: number;
}

export function createLayerBlendMaterial(scene: BABYLON.Scene, options: LayerBlendMaterialOptions = {}): LayerBlendMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error('Invalid passIndex ' + passIndex + ' for LayerBlend. Expected 0 <= passIndex < 1.');
  }
  const baseName = options.name ?? 'LayerBlendMaterial';
  const shaderName = `${baseName}_pass${passIndex}`;
  const vertexShaderName = `${shaderName}VertexShader`;
  const fragmentShaderName = `${shaderName}FragmentShader`;

  BABYLON.ShaderStore.ShadersStore[vertexShaderName] = LayerBlendVertexSource;
  BABYLON.ShaderStore.ShadersStore[fragmentShaderName] = LayerBlendFragmentSources[passIndex];

  const material = new BABYLON.ShaderMaterial(shaderName, scene, {
    vertex: shaderName,
    fragment: shaderName,
  }, {
    attributes: ['position', 'uv'],
    uniforms: [],
    samplers: ['src1', 'src2'],
    shaderLanguage: BABYLON.ShaderLanguage.GLSL,
  });

  const defaultSampler = new BABYLON.TextureSampler();
  defaultSampler.setParameters(
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    undefined,
    BABYLON.Texture.BILINEAR_SAMPLINGMODE,
  );
  const samplerState: Record<string, BABYLON.TextureSampler> = {};
  const textureState: Partial<Record<LayerBlendTextureName, BABYLON.BaseTexture | null>> = {};
  const applySamplerToTexture = (texture: BABYLON.BaseTexture | null, sampler: BABYLON.TextureSampler) => {
    if (!texture) return;
    const wrapU = sampler.wrapU;
    if (wrapU !== null && wrapU !== undefined) {
      texture.wrapU = wrapU;
    }
    const wrapV = sampler.wrapV;
    if (wrapV !== null && wrapV !== undefined) {
      texture.wrapV = wrapV;
    }
    const wrapR = sampler.wrapR;
    if (wrapR !== null && wrapR !== undefined) {
      texture.wrapR = wrapR;
    }
    texture.updateSamplingMode(sampler.samplingMode);
  };

  const handles: LayerBlendMaterialHandles = {
    material,
    setTexture: (name, texture) => {
      material.setTexture(name, texture);
      textureState[name] = texture;
      const sampler = samplerState[name] ?? defaultSampler;
      applySamplerToTexture(texture, sampler);
    },
    setTextureSampler: (name, sampler) => {
      samplerState[name] = sampler;
      const texture = textureState[name] ?? null;
      applySamplerToTexture(texture, sampler);
    },
    setUniforms: (_uniforms) => { },
  };

  return handles;
}

export class LayerBlendEffect extends CustomShaderEffect<LayerBlendUniforms, LayerBlendInputs> {
  effectName = 'LayerBlend'

  constructor(engine: BABYLON.Engine, inputs: LayerBlendInputs, width = 1280, height = 720, sampleMode: 'nearest' | 'linear' = 'linear', precision: RenderPrecision = 'half_float') {
    super(engine, inputs, {
      factory: (sceneRef, options) => createLayerBlendMaterial(sceneRef, options),
      textureInputKeys: ['src1', 'src2'],
      textureBindingKeys: ['src1', 'src2'],
      passTextureSources: LayerBlendPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src1',
      width,
      height,
      materialName: 'LayerBlendMaterial',
      sampleMode,
      precision,
      uniformMeta: LayerBlendUniformMeta,
    });
  }

  override setSrcs(inputs: Partial<LayerBlendInputs>): void {
    super.setSrcs(inputs);
  }

}