// Auto-generated by glsl fragment generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';
import { CustomShaderEffect, type ShaderSource, type RenderPrecision, type UniformDescriptor, type ShaderUniforms, type Dynamic } from '../shaderFXBabylon_GL';
export const PixelateVertexSource = `// Auto-generated by glsl fragment generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec3 position;
in vec2 uv;
out vec2 vUV;

void main() {
  gl_Position = vec4(position, 1.0);
  vUV = uv;
}`;
export const PixelateFragmentSources = [
  `// Auto-generated by glsl fragment generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec2 vUV;
out vec4 outColor;
uniform float uniforms_pixelSize;
uniform sampler2D src;

struct PixelateUniforms {
  float pixelSize; // 1.0 min=1.0 max=64.0 step=1.0
};

vec4 pass0(vec2 uv, PixelateUniforms uniforms, sampler2D src) {
  ivec2 dims = textureSize(src, 0);
  vec2 res = vec2(
    dims.x > 0 ? float(dims.x) : 1.0,
    dims.y > 0 ? float(dims.y) : 1.0
  );
  float size = max(uniforms.pixelSize, 1.0);
  vec2 pixelatedUV = floor(uv * res / size) * (size / res);
  return texture(src, pixelatedUV);
}

PixelateUniforms load_PixelateUniforms() {
  PixelateUniforms result;
  result.pixelSize = uniforms_pixelSize;
  return result;
}

void main() {
  PixelateUniforms uniforms_value = load_PixelateUniforms();
  vec2 uv_local = vUV;
  vec4 color = pass0(uv_local, uniforms_value, src);
  outColor = color;
}`, // pass0
] as const;
export const PixelatePassCount = 1 as const;
export const PixelatePrimaryTextureName = 'src' as const;

export const PixelatePassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const PixelateUniformMeta: UniformDescriptor[] = [
  {
    name: 'pixelSize',
    kind: 'f32',
    bindingName: 'uniforms_pixelSize',
    default: 1.0,
    ui: { min: 1, max: 64, step: 1 },
  },
];

export interface PixelateUniforms {
  pixelSize: number;
}

export function setPixelateUniforms(material: BABYLON.ShaderMaterial, uniforms: Partial<PixelateUniforms>): void {
  if (!uniforms) {
    return;
  }
  if (uniforms.pixelSize !== undefined) {
    material.setFloat('uniforms_pixelSize', uniforms.pixelSize);
  }
}

export type PixelateTextureName = 'src';
export interface PixelateInputs {
  src: ShaderSource;
}

export interface PixelateMaterialHandles {
  material: BABYLON.ShaderMaterial;
  setTexture(name: PixelateTextureName, texture: BABYLON.BaseTexture): void;
  setTextureSampler(name: PixelateTextureName, sampler: BABYLON.TextureSampler): void;
  setUniforms(uniforms: Partial<PixelateUniforms>): void;
}

export interface PixelateMaterialOptions {
  name?: string;
  passIndex?: number;
}

export function createPixelateMaterial(scene: BABYLON.Scene, options: PixelateMaterialOptions = {}): PixelateMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error('Invalid passIndex ' + passIndex + ' for Pixelate. Expected 0 <= passIndex < 1.');
  }
  const baseName = options.name ?? 'PixelateMaterial';
  const shaderName = `${baseName}_pass${passIndex}`;
  const vertexShaderName = `${shaderName}VertexShader`;
  const fragmentShaderName = `${shaderName}FragmentShader`;

  BABYLON.ShaderStore.ShadersStore[vertexShaderName] = PixelateVertexSource;
  BABYLON.ShaderStore.ShadersStore[fragmentShaderName] = PixelateFragmentSources[passIndex];

  const material = new BABYLON.ShaderMaterial(shaderName, scene, {
    vertex: shaderName,
    fragment: shaderName,
  }, {
    attributes: ['position', 'uv'],
    uniforms: ['uniforms_pixelSize'],
    samplers: ['src'],
    shaderLanguage: BABYLON.ShaderLanguage.GLSL,
  });

  const defaultSampler = new BABYLON.TextureSampler();
  defaultSampler.setParameters(
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    undefined,
    BABYLON.Texture.BILINEAR_SAMPLINGMODE,
  );
  const samplerState: Record<string, BABYLON.TextureSampler> = {};
  const textureState: Partial<Record<PixelateTextureName, BABYLON.BaseTexture | null>> = {};
  const applySamplerToTexture = (texture: BABYLON.BaseTexture | null, sampler: BABYLON.TextureSampler) => {
    if (!texture) return;
    const wrapU = sampler.wrapU;
    if (wrapU !== null && wrapU !== undefined) {
      texture.wrapU = wrapU;
    }
    const wrapV = sampler.wrapV;
    if (wrapV !== null && wrapV !== undefined) {
      texture.wrapV = wrapV;
    }
    const wrapR = sampler.wrapR;
    if (wrapR !== null && wrapR !== undefined) {
      texture.wrapR = wrapR;
    }
    texture.updateSamplingMode(sampler.samplingMode);
  };

  const handles: PixelateMaterialHandles = {
    material,
    setTexture: (name, texture) => {
      material.setTexture(name, texture);
      textureState[name] = texture;
      const sampler = samplerState[name] ?? defaultSampler;
      applySamplerToTexture(texture, sampler);
    },
    setTextureSampler: (name, sampler) => {
      samplerState[name] = sampler;
      const texture = textureState[name] ?? null;
      applySamplerToTexture(texture, sampler);
    },
    setUniforms: (values) => setPixelateUniforms(material, values),
  };

  return handles;
}

export class PixelateEffect extends CustomShaderEffect<PixelateUniforms, PixelateInputs> {
  effectName = 'Pixelate'

  constructor(engine: BABYLON.Engine, inputs: PixelateInputs, width = 1280, height = 720, sampleMode: 'nearest' | 'linear' = 'linear', precision: RenderPrecision = 'half_float') {
    super(engine, inputs, {
      factory: (sceneRef, options) => createPixelateMaterial(sceneRef, options),
      textureInputKeys: ['src'],
      textureBindingKeys: ['src'],
      passTextureSources: PixelatePassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      materialName: 'PixelateMaterial',
      sampleMode,
      precision,
      uniformMeta: PixelateUniformMeta,
    });
    this.setUniforms({
      pixelSize: 1.0,
    });
  }

  override setSrcs(inputs: Partial<PixelateInputs>): void {
    super.setSrcs(inputs);
  }

  override setUniforms(uniforms: { pixelSize?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.pixelSize !== undefined) {
      record['pixelSize'] = uniforms.pixelSize;
    }
    super.setUniforms(record);
  }
}