// Auto-generated by glsl fragment generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';
import { CustomShaderEffect, type ShaderSource, type RenderPrecision, type UniformDescriptor, type ShaderUniforms, type Dynamic } from '../shaderFXBabylon_GL';
export const PolygonMaskVertexSource = `// Auto-generated by glsl fragment generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec3 position;
in vec2 uv;
out vec2 vUV;

void main() {
  gl_Position = vec4(position, 1.0);
  vUV = uv;
}`;
export const PolygonMaskFragmentSources = [
  `// Auto-generated by glsl fragment generator. DO NOT EDIT.
#version 300 es
precision highp float;

in vec2 vUV;
out vec4 outColor;
uniform vec2 uniforms_points[64];
uniform int uniforms_pointCount;
uniform sampler2D src;

struct PolygonMaskUniforms {
  vec2 points[64];
  int pointCount;
};

bool pointInPolygon(vec2 pt, PolygonMaskUniforms uniforms) {
  int count = uniforms.pointCount;
  if (count < 3) {
    return true;
  }

  bool inside = false;
  int j = count - 1;

  for (int i = 0; i < 64; i++) {
    if (i >= count) {
      break;
    }
    vec2 pi = uniforms.points[i];
    vec2 pj = uniforms.points[j];
    bool intersects = (pi.y > pt.y) != (pj.y > pt.y);
    if (intersects) {
      float xCross = (pj.x - pi.x) * (pt.y - pi.y) / (pj.y - pi.y) + pi.x;
      if (pt.x < xCross) {
        inside = !inside;
      }
    }
    j = i;
  }

  return inside;
}

vec4 pass0(vec2 uv, PolygonMaskUniforms uniforms, sampler2D src) {
  vec4 color = texture(src, uv);
  if (!pointInPolygon(uv, uniforms)) {
    return vec4(0.0, 0.0, 0.0, 0.0);
  }
  return color;
}

PolygonMaskUniforms load_PolygonMaskUniforms() {
  PolygonMaskUniforms result;
  result.points = uniforms_points;
  result.pointCount = uniforms_pointCount;
  return result;
}

void main() {
  PolygonMaskUniforms uniforms_value = load_PolygonMaskUniforms();
  vec2 uv_local = vUV;
  vec4 color = pass0(uv_local, uniforms_value, src);
  outColor = color;
}`, // pass0
] as const;
export const PolygonMaskPassCount = 1 as const;
export const PolygonMaskPrimaryTextureName = 'src' as const;

export const PolygonMaskPassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const PolygonMaskUniformMeta: UniformDescriptor[] = [
  {
    name: 'points',
    kind: 'vec2f',
    isArray: true,
    arraySize: 64,
    bindingName: 'uniforms_points',
  },
  {
    name: 'pointCount',
    kind: 'i32',
    bindingName: 'uniforms_pointCount',
  },
];

export interface Vec2Like { x: number; y: number }
export interface Vec3Like { x: number; y: number; z: number }
export interface Vec4Like { x: number; y: number; z: number; w: number }

function packVec2Array(arr: Vec2Like[]): number[] {
  return arr.flatMap(v => [v.x, v.y]);
}

export interface PolygonMaskUniforms {
  points: Vec2Like[];
  pointCount: number;
}

export function setPolygonMaskUniforms(material: BABYLON.ShaderMaterial, uniforms: Partial<PolygonMaskUniforms>): void {
  if (!uniforms) {
    return;
  }
  if (uniforms.points !== undefined) {
    material.setArray2('uniforms_points', packVec2Array(uniforms.points));
  }
  if (uniforms.pointCount !== undefined) {
    material.setInt('uniforms_pointCount', uniforms.pointCount);
  }
}

export type PolygonMaskTextureName = 'src';
export interface PolygonMaskInputs {
  src: ShaderSource;
}

export interface PolygonMaskMaterialHandles {
  material: BABYLON.ShaderMaterial;
  setTexture(name: PolygonMaskTextureName, texture: BABYLON.BaseTexture): void;
  setTextureSampler(name: PolygonMaskTextureName, sampler: BABYLON.TextureSampler): void;
  setUniforms(uniforms: Partial<PolygonMaskUniforms>): void;
}

export interface PolygonMaskMaterialOptions {
  name?: string;
  passIndex?: number;
}

export function createPolygonMaskMaterial(scene: BABYLON.Scene, options: PolygonMaskMaterialOptions = {}): PolygonMaskMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error('Invalid passIndex ' + passIndex + ' for PolygonMask. Expected 0 <= passIndex < 1.');
  }
  const baseName = options.name ?? 'PolygonMaskMaterial';
  const shaderName = `${baseName}_pass${passIndex}`;
  const vertexShaderName = `${shaderName}VertexShader`;
  const fragmentShaderName = `${shaderName}FragmentShader`;

  BABYLON.ShaderStore.ShadersStore[vertexShaderName] = PolygonMaskVertexSource;
  BABYLON.ShaderStore.ShadersStore[fragmentShaderName] = PolygonMaskFragmentSources[passIndex];

  const material = new BABYLON.ShaderMaterial(shaderName, scene, {
    vertex: shaderName,
    fragment: shaderName,
  }, {
    attributes: ['position', 'uv'],
    uniforms: ['uniforms_points', 'uniforms_pointCount'],
    samplers: ['src'],
    shaderLanguage: BABYLON.ShaderLanguage.GLSL,
  });

  const defaultSampler = new BABYLON.TextureSampler();
  defaultSampler.setParameters(
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    BABYLON.Texture.CLAMP_ADDRESSMODE,
    undefined,
    BABYLON.Texture.BILINEAR_SAMPLINGMODE,
  );
  const samplerState: Record<string, BABYLON.TextureSampler> = {};
  const textureState: Partial<Record<PolygonMaskTextureName, BABYLON.BaseTexture | null>> = {};
  const applySamplerToTexture = (texture: BABYLON.BaseTexture | null, sampler: BABYLON.TextureSampler) => {
    if (!texture) return;
    const wrapU = sampler.wrapU;
    if (wrapU !== null && wrapU !== undefined) {
      texture.wrapU = wrapU;
    }
    const wrapV = sampler.wrapV;
    if (wrapV !== null && wrapV !== undefined) {
      texture.wrapV = wrapV;
    }
    const wrapR = sampler.wrapR;
    if (wrapR !== null && wrapR !== undefined) {
      texture.wrapR = wrapR;
    }
    texture.updateSamplingMode(sampler.samplingMode);
  };

  const handles: PolygonMaskMaterialHandles = {
    material,
    setTexture: (name, texture) => {
      material.setTexture(name, texture);
      textureState[name] = texture;
      const sampler = samplerState[name] ?? defaultSampler;
      applySamplerToTexture(texture, sampler);
    },
    setTextureSampler: (name, sampler) => {
      samplerState[name] = sampler;
      const texture = textureState[name] ?? null;
      applySamplerToTexture(texture, sampler);
    },
    setUniforms: (values) => setPolygonMaskUniforms(material, values),
  };

  return handles;
}

export class PolygonMaskEffect extends CustomShaderEffect<PolygonMaskUniforms, PolygonMaskInputs> {
  effectName = 'PolygonMask'

  constructor(engine: BABYLON.Engine, inputs: PolygonMaskInputs, width = 1280, height = 720, sampleMode: 'nearest' | 'linear' = 'linear', precision: RenderPrecision = 'half_float') {
    super(engine, inputs, {
      factory: (sceneRef, options) => createPolygonMaskMaterial(sceneRef, options),
      textureInputKeys: ['src'],
      textureBindingKeys: ['src'],
      passTextureSources: PolygonMaskPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      materialName: 'PolygonMaskMaterial',
      sampleMode,
      precision,
      uniformMeta: PolygonMaskUniformMeta,
    });
    this.setUniforms({
    });
  }

  override setSrcs(inputs: Partial<PolygonMaskInputs>): void {
    super.setSrcs(inputs);
  }

  override setUniforms(uniforms: { points?: Dynamic<Vec2Like[]>; pointCount?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.points !== undefined) {
      record['points'] = uniforms.points;
    }
    if (uniforms.pointCount !== undefined) {
      record['pointCount'] = uniforms.pointCount;
    }
    super.setUniforms(record);
  }
}