// Auto-generated by wgsl fragment generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';
import { CustomShaderEffect, type ShaderSource, type RenderPrecision, type UniformDescriptor, type ShaderUniforms, type Dynamic } from '../shaderFXBabylon';
export const DyeAdvectionVertexSource = `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
attribute position: vec3<f32>;
attribute uv: vec2<f32>;
varying vUV: vec2<f32>;

#define CUSTOM_VERTEX_DEFINITIONS
@vertex
fn main(input : VertexInputs) -> FragmentInputs {
#define CUSTOM_VERTEX_MAIN_BEGIN
  vertexOutputs.position = vec4<f32>(vertexInputs.position, 1.0);
  vertexOutputs.vUV = vertexInputs.uv;
#define CUSTOM_VERTEX_MAIN_END
}

`;
export const DyeAdvectionFragmentSources = [
  `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
varying vUV: vec2<f32>;
uniform uniforms_timeStep: f32;
uniform uniforms_dissipation: f32;
var dye: texture_2d<f32>;
var dyeSampler: sampler;
var velocity: texture_2d<f32>;
var velocitySampler: sampler;

// Source fragment function
struct DyeAdvectionUniforms {
  timeStep: f32,
  dissipation: f32,
};

fn pass0(
  uv: vec2f,
  uniforms: DyeAdvectionUniforms,
  dye: texture_2d<f32>,
  dyeSampler: sampler,
  velocity: texture_2d<f32>,
  velocitySampler: sampler,
) -> vec4f {
  let vel = textureSample(velocity, velocitySampler, uv).xy;
  let dims = textureDimensions(velocity);
  let texel = vec2f(
    select(1.0 / f32(dims.x), 0.0, dims.x == 0u),
    select(1.0 / f32(dims.y), 0.0, dims.y == 0u),
  );
  let prevUv = clamp(uv - vel * uniforms.timeStep * texel, vec2f(0.0), vec2f(1.0));
  
  let advectedDye = textureSample(dye, dyeSampler, prevUv).xyz;
  
  let finalDye = advectedDye * uniforms.dissipation;
  
  return vec4f(finalDye, 1.0);
}

fn load_DyeAdvectionUniforms() -> DyeAdvectionUniforms {
  return DyeAdvectionUniforms(
  uniforms.uniforms_timeStep,
  uniforms.uniforms_dissipation
  );
}

#define CUSTOM_FRAGMENT_DEFINITIONS
@fragment
fn main(input: FragmentInputs) -> FragmentOutputs {
#define CUSTOM_FRAGMENT_MAIN_BEGIN
  let uniforms_value = load_DyeAdvectionUniforms();
  let uv_local = fragmentInputs.vUV;
  let color = pass0(uv_local, uniforms_value, dye, dyeSampler, velocity, velocitySampler);
  fragmentOutputs.color = color;
#define CUSTOM_FRAGMENT_MAIN_END
}

`, // pass0
] as const;
export const DyeAdvectionPassCount = 1 as const;
export const DyeAdvectionPrimaryTextureName = 'dye' as const;

export const DyeAdvectionPassTextureSources = [
  [
    { binding: 'dye', source: { kind: 'input', key: 'dye' } },
    { binding: 'velocity', source: { kind: 'input', key: 'velocity' } },
  ],
] as const;

export const DyeAdvectionUniformMeta: UniformDescriptor[] = [
  {
    name: 'timeStep',
    kind: 'f32',
    bindingName: 'uniforms_timeStep',
  },
  {
    name: 'dissipation',
    kind: 'f32',
    bindingName: 'uniforms_dissipation',
  },
];

export interface DyeAdvectionUniforms {
  timeStep: number;
  dissipation: number;
}

export function setDyeAdvectionUniforms(material: BABYLON.ShaderMaterial, uniforms: Partial<DyeAdvectionUniforms>): void {
  if (!uniforms) {
    return;
  }
  if (uniforms.timeStep !== undefined) {
    material.setFloat('uniforms_timeStep', uniforms.timeStep);
  }
  if (uniforms.dissipation !== undefined) {
    material.setFloat('uniforms_dissipation', uniforms.dissipation);
  }
}

export type DyeAdvectionTextureName = 'dye' | 'velocity';
export interface DyeAdvectionInputs {
  dye: ShaderSource;
  velocity: ShaderSource;
}

export interface DyeAdvectionMaterialHandles {
  material: BABYLON.ShaderMaterial;
  setTexture(name: DyeAdvectionTextureName, texture: BABYLON.BaseTexture): void;
  setTextureSampler(name: DyeAdvectionTextureName, sampler: BABYLON.TextureSampler): void;
  setUniforms(uniforms: Partial<DyeAdvectionUniforms>): void;
}

export interface DyeAdvectionMaterialOptions {
  name?: string;
  passIndex?: number;
}

export function createDyeAdvectionMaterial(scene: BABYLON.Scene, options: DyeAdvectionMaterialOptions = {}): DyeAdvectionMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for DyeAdvection. Expected 0 <= passIndex < 1.`);
  }
  const baseName = options.name ?? 'DyeAdvectionMaterial';
  const shaderName = `${baseName}_pass${passIndex}`;
  // Register shaders in the WGSL store to enable preprocessor
  const vertexShaderName = `${shaderName}VertexShader`;
  const fragmentShaderName = `${shaderName}FragmentShader`;
  
  BABYLON.ShaderStore.ShadersStoreWGSL[vertexShaderName] = DyeAdvectionVertexSource;
  BABYLON.ShaderStore.ShadersStoreWGSL[fragmentShaderName] = DyeAdvectionFragmentSources[passIndex];
  
  const material = new BABYLON.ShaderMaterial(shaderName, scene, {
    vertex: shaderName,
    fragment: shaderName,
  }, {
    attributes: ['position', 'uv'],
    uniforms: ['uniforms_timeStep', 'uniforms_dissipation'],
    samplers: ['dye', 'velocity'],
    samplerObjects: ['dyeSampler', 'velocitySampler'],
    shaderLanguage: BABYLON.ShaderLanguage.WGSL,
  });

  const samplerLookup = { 'dye': 'dyeSampler', 'velocity': 'velocitySampler' } as const;

  const handles: DyeAdvectionMaterialHandles = {
    material,
    setTexture: (name, texture) => material.setTexture(name, texture),
    setTextureSampler: (name, sampler) => material.setTextureSampler(samplerLookup[name], sampler),
    setUniforms: (values) => setDyeAdvectionUniforms(material, values),
  };

  return handles;
}

export class DyeAdvectionEffect extends CustomShaderEffect<DyeAdvectionUniforms, DyeAdvectionInputs> {
  effectName = 'DyeAdvection'

  constructor(engine: BABYLON.WebGPUEngine, inputs: DyeAdvectionInputs, width = 1280, height = 720, sampleMode: 'nearest' | 'linear' = 'linear', precision: RenderPrecision = 'half_float') {
    super(engine, inputs, {
      factory: (sceneRef, options) => createDyeAdvectionMaterial(sceneRef, options),
      textureInputKeys: ['dye', 'velocity'],
      textureBindingKeys: ['dye', 'velocity'],
      passTextureSources: DyeAdvectionPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'dye',
      width,
      height,
      materialName: 'DyeAdvectionMaterial',
      sampleMode,
      precision,
      uniformMeta: DyeAdvectionUniformMeta,
    })
  }

  override setSrcs(inputs: Partial<DyeAdvectionInputs>): void {
    super.setSrcs(inputs);
  }

  override setUniforms(uniforms: { timeStep?: Dynamic<number>, dissipation?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.timeStep !== undefined) {
      record['timeStep'] = uniforms.timeStep;
    }
    if (uniforms.dissipation !== undefined) {
      record['dissipation'] = uniforms.dissipation;
    }
    super.setUniforms(record);
  }
}

