// Auto-generated by wgsl fragment generator. DO NOT EDIT.
import * as BABYLON from 'babylonjs';
import { CustomShaderEffect, type ShaderSource, type RenderPrecision } from '../shaderFXBabylon';
export const GradientSubtractionVertexSource = `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
attribute position: vec3<f32>;
attribute uv: vec2<f32>;
varying vUV: vec2<f32>;

#define CUSTOM_VERTEX_DEFINITIONS
@vertex
fn main(input : VertexInputs) -> FragmentInputs {
#define CUSTOM_VERTEX_MAIN_BEGIN
  vertexOutputs.position = vec4<f32>(vertexInputs.position, 1.0);
  vertexOutputs.vUV = vertexInputs.uv;
#define CUSTOM_VERTEX_MAIN_END
}

`;
export const GradientSubtractionFragmentSources = [
  `// Auto-generated by wgsl fragment generator. DO NOT EDIT.
varying vUV: vec2<f32>;
var velocity: texture_2d<f32>;
var velocitySampler: sampler;
var pressure: texture_2d<f32>;
var pressureSampler: sampler;

// Source fragment function
fn texelSize(tex: texture_2d<f32>) -> vec2f {
  let dims = textureDimensions(tex);
  return 1.0 / vec2f(f32(dims.x), f32(dims.y));
}

fn pass0(
  uv: vec2f,
  velocity: texture_2d<f32>,
  velocitySampler: sampler,
  pressure: texture_2d<f32>,
  pressureSampler: sampler,
) -> vec4f {
  let vel = textureSample(velocity, velocitySampler, uv).xy;
  let texel = texelSize(pressure);
  
  let center = textureSample(pressure, pressureSampler, clamp(uv, vec2f(0.0), vec2f(1.0))).x;
  
  let leftUv = uv - vec2f(texel.x, 0.0);
  var pL = textureSample(pressure, pressureSampler, clamp(leftUv, vec2f(0.0), vec2f(1.0))).x;
  if (leftUv.x < 0.0) {
    pL = center;
  }
  
  let rightUv = uv + vec2f(texel.x, 0.0);
  var pR = textureSample(pressure, pressureSampler, clamp(rightUv, vec2f(0.0), vec2f(1.0))).x;
  if (rightUv.x > 1.0) {
    pR = center;
  }
  
  let bottomUv = uv - vec2f(0.0, texel.y);
  var pB = textureSample(pressure, pressureSampler, clamp(bottomUv, vec2f(0.0), vec2f(1.0))).x;
  if (bottomUv.y < 0.0) {
    pB = center;
  }
  
  let topUv = uv + vec2f(0.0, texel.y);
  var pT = textureSample(pressure, pressureSampler, clamp(topUv, vec2f(0.0), vec2f(1.0))).x;
  if (topUv.y > 1.0) {
    pT = center;
  }
  
  let gradient = vec2f(pR - pL, pT - pB);
  
  let projectedVel = vel - gradient;
  
  return vec4f(projectedVel, 0.0, 1.0);
}

#define CUSTOM_FRAGMENT_DEFINITIONS
@fragment
fn main(input: FragmentInputs) -> FragmentOutputs {
#define CUSTOM_FRAGMENT_MAIN_BEGIN
  let uv_local = fragmentInputs.vUV;
  let color = pass0(uv_local, velocity, velocitySampler, pressure, pressureSampler);
  fragmentOutputs.color = color;
#define CUSTOM_FRAGMENT_MAIN_END
}

`, // pass0
] as const;
export const GradientSubtractionPassCount = 1 as const;
export const GradientSubtractionPrimaryTextureName = 'velocity' as const;

export const GradientSubtractionPassTextureSources = [
  [
    { binding: 'velocity', source: { kind: 'input', key: 'velocity' } },
    { binding: 'pressure', source: { kind: 'input', key: 'pressure' } },
  ],
] as const;

export type GradientSubtractionUniforms = Record<string, never>;
export function setGradientSubtractionUniforms(_material: BABYLON.ShaderMaterial, _uniforms: Partial<GradientSubtractionUniforms>): void {}

export type GradientSubtractionTextureName = 'velocity' | 'pressure';
export interface GradientSubtractionInputs {
  velocity: ShaderSource;
  pressure: ShaderSource;
}

export interface GradientSubtractionMaterialHandles {
  material: BABYLON.ShaderMaterial;
  setTexture(name: GradientSubtractionTextureName, texture: BABYLON.BaseTexture): void;
  setTextureSampler(name: GradientSubtractionTextureName, sampler: BABYLON.TextureSampler): void;
  setUniforms(uniforms: Partial<GradientSubtractionUniforms>): void;
}

export interface GradientSubtractionMaterialOptions {
  name?: string;
  passIndex?: number;
}

export function createGradientSubtractionMaterial(scene: BABYLON.Scene, options: GradientSubtractionMaterialOptions = {}): GradientSubtractionMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for GradientSubtraction. Expected 0 <= passIndex < 1.`);
  }
  const baseName = options.name ?? 'GradientSubtractionMaterial';
  const shaderName = `${baseName}_pass${passIndex}`;
  // Register shaders in the WGSL store to enable preprocessor
  const vertexShaderName = `${shaderName}VertexShader`;
  const fragmentShaderName = `${shaderName}FragmentShader`;
  
  BABYLON.ShaderStore.ShadersStoreWGSL[vertexShaderName] = GradientSubtractionVertexSource;
  BABYLON.ShaderStore.ShadersStoreWGSL[fragmentShaderName] = GradientSubtractionFragmentSources[passIndex];
  
  const material = new BABYLON.ShaderMaterial(shaderName, scene, {
    vertex: shaderName,
    fragment: shaderName,
  }, {
    attributes: ['position', 'uv'],
    uniforms: [],
    samplers: ['velocity', 'pressure'],
    samplerObjects: ['velocitySampler', 'pressureSampler'],
    shaderLanguage: BABYLON.ShaderLanguage.WGSL,
  });

  const samplerLookup = { 'velocity': 'velocitySampler', 'pressure': 'pressureSampler' } as const;

  const handles: GradientSubtractionMaterialHandles = {
    material,
    setTexture: (name, texture) => material.setTexture(name, texture),
    setTextureSampler: (name, sampler) => material.setTextureSampler(samplerLookup[name], sampler),
    setUniforms: () => {},
  };

  return handles;
}

export class GradientSubtractionEffect extends CustomShaderEffect<GradientSubtractionUniforms, GradientSubtractionInputs> {
  effectName = 'GradientSubtraction'

  constructor(engine: BABYLON.WebGPUEngine, inputs: GradientSubtractionInputs, width = 1280, height = 720, sampleMode: 'nearest' | 'linear' = 'linear', precision: RenderPrecision = 'half_float') {
    super(engine, inputs, {
      factory: (sceneRef, options) => createGradientSubtractionMaterial(sceneRef, options),
      textureInputKeys: ['velocity', 'pressure'],
      textureBindingKeys: ['velocity', 'pressure'],
      passTextureSources: GradientSubtractionPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'velocity',
      width,
      height,
      materialName: 'GradientSubtractionMaterial',
      sampleMode,
      precision,
    })
  }

  override setSrcs(inputs: Partial<GradientSubtractionInputs>): void {
    super.setSrcs(inputs);
  }
}

